package com.bridge.sterling.consts;

import com.yantra.yfc.util.YFCLocale;



public class XMLLiterals {
public static final String CATEGORY = "Category";
public static final String CATEGORY_ID = "CategoryID";
public static final String ORGANIZATION_CODE = "OrganizationCode";
public static final String CATEGORY_LIST = "CategoryList";
public static final String GET_CATEGORY_LIST = "getCategoryList";
public static final String CATEGORY_DOMAIN = "CategoryDomain";
public static final String DESCRIPTION = "Description";
public static final String IS_CLASSIFICATION = "IsClassification";
public static final String CATEGORY_PATH = "CategoryPath";
public static final String CREATE_CATEGORY = "createCategory";
public static final String MANAGE_CATEGORY = "manageCategory";
public static final String GET_UNPUBLISHED_CATEGORIES= "GetUnpublishedCategories";
public static final String CATEGORY_KEY = "CategoryKey";
public static final String STATUS = "Status";
public static final String ORGANIZATION = "Organization";
public static final String SHIP_NODE_CODE = "ShipNode";
public static final String SHIPNODE = "ShipNode";
public static final String GET_SHIP_NODE_LIST = "getShipNodeList";
public static final String SHIPNODE_LIST = "ShipNodeList";
public static final String OWNERKEY = "OwnerKey";
public static final String CAPACITYORGCODE = "CapacityOrganizationCode";
public static final String PMENTERPRISEKEY = "PrimaryEnterpriseKey";
public static final String SHIP_NODE_LIST = "ShipNodeList";
public static final String INDIGO_CA = "Indigo_CA";
public static final String STORE_LIST = "StoreList";
public static final String SHIPNODEKEY = "ShipnodeKey";
public static final String ACTION = "Action";
public static final String DELETE = "Delete";
public static final String ITEM = "Item";
public static final String ITEM_LIST = "ItemList";
public static final String ITEM_ID = "ItemID";
public static final String SYNC_TS = "SyncTS";
public static final String GET_ITEM_LIST_API = "getItemList";
public static final String CLASSIFICATION_CODES = "ClassificationCodes";
public static final String PRODUCT_LINE = "ProductLine";
public static final String MODIFY_CATEGORY_ITEM = "modifyCategoryItem";
public static final String MODIFY_CATEGORY_ITEMS = "ModifyCategoryItems";
public static final String CALLING_ORGANIZATION_CODE = "CallingOrganizationCode";
public static final String CATEGORY_ITEM_LIST = "CategoryItemList";
public static final String CATEGORY_ITEM = "CategoryItem";
public static final String UNIT_OF_MEASURE = "UnitOfMeasure";
public static final String MANAGE_ITEM = "manageItem";
public static final String COMMODITY_CODE = "CommodityCode";
public static final String SHORT_DESCRIPTION = "ShortDescription" ;
public static final String DEPARTMENT_LIST = "DepartmentList";
public static final String DEPARTMENT = "Department";
public static final String DEPARTMENT_KEY = "DepartmentKey";
public static final String DEPARTMENT_NAME = "DepartmentName";
public static final String DEPARTMENT_CODE = "DepartmentCode";
public static final String CATEGORY_FILTER = "CategoryFilter";
public static final String MODIFY_USER_HIERARCHY = "modifyUserHierarchy";
public static final String CREATE_USER_HIERARCHY = "createUserHierarchy";
public static final String GET_USER_LIST = "getUserList";
public static final String CREATE_ORGANIZATION_HIERARCHY = "createOrganizationHierarchy";
public static final String MODIFY_ORGANIZATION_HIERARCHY = "modifyOrganizationHierarchy";
public static final String USER = "User";
public static final String LOGIN_ID = "Loginid";
public static final String DISPLAY_USER_ID = "DisplayUserID";
public static final String ENTERPRISE_CODE = "EnterpriseCode";
public static final String USER_LIST = "UserList";
public static final String ACTIVATE_FLAG = "Activateflag";
public static final String ACTIVATEFLAG = "ActivateFlag";
public static final String NODE = "Node";
public static final String MANAGE_ORGANIZATION_HIERARCHY = "manageOrganizationHierarchy";
public static final String GET_CALENDAR_LIST="getCalendarList";
public static final String CALENDAR="Calendar";
public static final String CALENDAR_KEY="CalendarKey";
public static final String CALENDAR_LIST="CalendarList";
public static final String EFFECTIVE_TO_DATE ="EffectiveToDate";
public static final String EFFECTIVE_FROM_DATE="EffectiveFromDate";
public static final String EFFECTIVE_PERIODS ="EffectivePeriods";
public static final String CREATE_CALENDAR = "createCalendar";
public static final String CALENDER_ID = "CalendarId";
public static final String EFFECTIVE_PERIOD = "EffectivePeriod";
public static final String SHIFTS = "Shifts";
public static final String SHIFT = "Shift";
public static final String SHIFT_NAME = "ShiftName";
public static final String SHIFT_START_TIME="ShiftStartTime";
public static final String SHIFT_END_TIME="ShiftEndTime";	
}
